### ISSUE TITLE
Q: 半角カタカナになっているはどうして？

### ISSUE THREAD

**Issue by InoueKenichi** [Koya-SI/R.U-Band#1]
https://github.com/Koya-SI/R.U-Band/blob/ad4d8bafa594668f6459dbbc4048432d543822f8/RBand.java#L3

**Comment by InoueKenichi** [comment]
@Koya-SI

**Comment by Koya-SI** [comment]
意図はなく、間違いだったので修正しました。

**Comment by Koya-SI** [comment]
https://github.com/Koya-SI/R.U-Band/commit/e64097d8eb8c75d9b3cbcffaa0fc64eb2d52bf34

**Comment by InoueKenichi** [comment]
修正を確認したのでクローズします。
